### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by psexton** [sheljohn/deck#4]
Is this code available under an open source license? I'm in the market for a new JSON parser...

**Comment by sheljohn** [comment]
Hi there, I'm really sorry it took me so long to see your message, GitHub doesn't seem to prioritise notifications on my own repositories over the ones I follow. Anyway to answer your question, I added a license a while ago now (AGPLv3). To break it down into simple terms; any use of the code is permitted, without warranty, provided that copyrights are retained, and that any modification is made freely available under the same terms.
